version: '3'

services:
  db:
    image: postgres:17
    container_name: ca_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5446:5432"
    volumes:
      - ../pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: ca_backend
    restart: unless-stopped
    user: root
    env_file:
      - .env
    ports:
      - "8808:8000"
    volumes:
      - ./backend/app:/app
    depends_on:
      - db
    command: bash -c "python manage.py runserver 0.0.0.0:8000"

  frontend:
    image: node:22-bookworm
    working_dir: /app
    container_name: ca_frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5174:5174"
    volumes:
      - ./frontend/app:/app
    command: |
      sh -c "npm install && npm run dev"
