filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/logs/*.log
      - /usr/share/filebeat/logs/management_logs/**/*.log

    multiline.pattern: '^\['
    multiline.negate: true
    multiline.match: after
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
